apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  labels:
    app: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: ghcr.io/adityachaurasiya0112-code/gitops-platform:b79fee8e1fa54744bd0c00852028f4da806018a5
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v2"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
