apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      values: |
        grafana:
          service:
            type: NodePort
            nodePort: 30300
          admin:
            existingSecret: grafana-admin
            userKey: admin-user
            passwordKey: admin-password
          defaultDashboardsTimezone: Asia/Kolkata
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
        prometheus:
          prometheusSpec:
            retention: 3d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 100m
                memory: 400Mi
              limits:
                memory: 800Mi
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 100Mi
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

